routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Auth\RedirectController@redirect')->middleware('auth');

Route::group(['middleware' => ['auth']], function () {

    //PAGINA PRINCIPAL
    Route::get('/home', 'HomeController@index')
        ->name('home');

    //PERFIL PESSOAL
    Route::get('/my-profile', 'UserController@myProfile')
        ->name('myprofile.index');

    Route::get('/my-profile/edit', 'UserController@myProfileEdit')
        ->name('myprofile.edit');

    //COLEÇÕES AMIGOS E REVISTAS
    Route::get('colecoes/{colecao}/itens', 'ColecaoController@listItens')
        ->name('colecoes.itens.list');

    Route::get('amigos/list', 'AmigoController@list')
        ->name('amigos.list');

    Route::get('revistas/list', 'RevistaController@list')
        ->name('revistas.list');

    Route::get('revistas/tipos', 'RevistaController@tipos')
        ->name('revistas.tipos');

    Route::post('revistas/{revista}/marcar-para-venda', 'RevistaController@marcarParaVenda')
        ->name('revistas.marcar-para-venda');

    Route::post('revistas/{revista}/desmarcar-para-venda', 'RevistaController@desmarcarParaVenda')
        ->name('revistas.desmarcar-para-venda');

    Route::post('emprestimos/{emprestimo}/devolver', 'EmprestimoController@devolver')
        ->name('emprestimos.devolver');

    Route::get('users/list', 'UserController@list')
        ->name('users.list');

    Route::get('search', 'BuscaController@index')
        ->name('search.index');

    //CRUDS
    Route::resource('users', 'UserController');
    Route::resource('titulos', 'TituloController');
    Route::resource('colecoes', 'ColecaoController');
    Route::resource('revistas', 'RevistaController');
    Route::resource('amigos', 'AmigoController');
    Route::resource('emprestimos', 'EmprestimoController');
    Route::resource('mensagens', 'MensagemController');
    Route::resource('comentarios', 'ComentarioController');
    Route::resource('lista', 'ListaDeDesejosController');

});

resources/views/colecoes/another_user_index.blade.php
@extends('template.template')

@section('breacumbs')
    <ol class="breadcrumb hidden-xs">
        <li class="active">
            <a href="{{ route('home') }}">
                <i class="voyager-home" ></i> Principal
            </a>
        </li>
        <li>Coleções</li>
    </ol>
@endsection

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-archive"></i>
            <span> {{ 'Coleções do usuario: ' .$nome }}</span>
        </h1>
    </div>

    <div id="gradient_bg"></div>
@endsection


@section('content')
    <div class="page-content container-fluid">
        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ HTML::ul($errors->all()) }}
                </div>
            @endif

            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                    <table  class="table datatable-export" style="width:100%">
                                        <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Autor</th>
                                            <th>Resumo</th>
                                            <th>Nº de volumes lançados</th>
                                            <th>Nº de itens da coleção</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @forelse($colecoes as $colecao)
                                            <tr>
                                                <td>{{ $colecao->titulo->nome }}</td>
                                                <td>{{ $colecao->titulo->autor }}</td>
                                                <td class="col-lg-5" style="text-align: left">{{ $colecao->titulo->resumo }}</td>
                                                <td>{{ $colecao->total_volumes }}</td>
                                                <td>{{ $colecao->itens->count() }}</td>
                                                <td id="bread-actions" align="center">

                                                    <a class="btn btn-sm btn-success pull-center view"
                                                       href="{{ route('colecoes.itens.list', $colecao->id) }}"
                                                       title="Vizualizar"
                                                    >
                                                        <i class="not-active voyager-list"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="6" align="center">Nenhum dado cadastrado até o momento</td>
                                            </tr>
                                        @endforelse

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/colecoes/index.blade.php
@extends('template.template')

@section('breacumbs')
    <ol class="breadcrumb hidden-xs">
        <li class="active">
            <a href="{{ route('home') }}">
                <i class="voyager-home" ></i> Principal
            </a>
        </li>
        <li>Coleções</li>
    </ol>
@endsection

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-archive"></i>
            <span> {{'Coleções'}} </span>
        </h1>
        <a class="btn btn-success btn-add-new openModal"
           data-toggle="modal"
           data-target="#formModal"
           data-action="{{ route('colecoes.store') }}"
           data-method="{{ 'POST' }}"
           data-title="{{ " Adicionar Cadastro " }}"
        >
            <i class="not-active voyager-plus"></i> {{ 'Adicionar item' }}
        </a>
    </div>

    <div id="gradient_bg"></div>
@endsection


@section('content')
    <div class="page-content container-fluid">
        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ HTML::ul($errors->all()) }}
                </div>
            @endif

            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                    <table  class="table datatable-export" style="width:100%">
                                        <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Autor</th>
                                            <th>Resumo</th>
                                            <th>Nº de volumes lançados</th>
                                            <th>Nº de itens da coleção</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @forelse($colecoes as $colecao)
                                            <tr>
                                                <td>{{ $colecao->titulo->nome }}</td>
                                                <td>{{ $colecao->titulo->autor }}</td>
                                                <td class="col-lg-5" style="text-align: left">{{ $colecao->titulo->resumo }}</td>
                                                <td>{{ $colecao->total_volumes }}</td>
                                                <td>{{ $colecao->itens->count() }}</td>
                                                <td id="bread-actions" align="center">

                                                    <a class="btn btn-sm btn-success pull-center view"
                                                       href="{{ route('colecoes.itens.list', $colecao->id) }}"
                                                       title="Vizualizar"
                                                    >
                                                        <i class="not-active voyager-list"></i>
                                                    </a>

                                                    <button title="Editar" class="btn btn-sm btn-primary pull-center edit openModal"
                                                            data-toggle="modal"
                                                            data-target="#formModal"
                                                            data-action="{{route('colecoes.update', $colecao->id)}}"
                                                            data-method="{{'PUT'}}"
                                                            data-title="{{ " Alterar Cadastro " }}"
                                                            data-id="{{ $colecao->id }}"
                                                    >
                                                        <i class="not-active voyager-edit" disabled="true"></i>
                                                    </button>

                                                    <button title="Delete" class="btn btn-sm btn-danger pull-center delete"
                                                            href="#"
                                                            data-action="{{ route('colecoes.destroy', $colecao->id) }}"
                                                            data-redirect="{{ route('colecoes.index') }}"
                                                    >
                                                        <i class="not-active voyager-trash"></i>
                                                    </button>

                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="6" align="center">Nenhum dado cadastrado até o momento</td>
                                            </tr>
                                        @endforelse

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <colecao></colecao>


@endsection