routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Auth\RedirectController@redirect')->middleware('auth');

Route::group(['middleware' => ['auth']], function () {

    //PAGINA PRINCIPAL
    Route::get('/home', 'HomeController@index')
        ->name('home');

    //PERFIL PESSOAL
    Route::get('/my-profile', 'UserController@myProfile')
        ->name('myprofile.index');

    Route::get('/my-profile/edit', 'UserController@myProfileEdit')
        ->name('myprofile.edit');

    //COLEÇÕES AMIGOS E REVISTAS
    Route::get('colecoes/{colecao}/itens', 'ColecaoController@listItens')
        ->name('colecoes.itens.list');

    Route::get('amigos/list', 'AmigoController@list')
        ->name('amigos.list');

    Route::get('revistas/list', 'RevistaController@list')
        ->name('revistas.list');

    Route::get('revistas/tipos', 'RevistaController@tipos')
        ->name('revistas.tipos');

    Route::post('revistas/{revista}/marcar-para-venda', 'RevistaController@marcarParaVenda')
        ->name('revistas.marcar-para-venda');

    Route::post('revistas/{revista}/desmarcar-para-venda', 'RevistaController@desmarcarParaVenda')
        ->name('revistas.desmarcar-para-venda');

    Route::post('emprestimos/{emprestimo}/devolver', 'EmprestimoController@devolver')
        ->name('emprestimos.devolver');

    Route::get('users/list', 'UserController@list')
        ->name('users.list');

    Route::get('search', 'BuscaController@index')
        ->name('search.index');

    //CRUDS
    Route::resource('users', 'UserController');
    Route::resource('titulos', 'TituloController');
    Route::resource('colecoes', 'ColecaoController');
    Route::resource('revistas', 'RevistaController');
    Route::resource('amigos', 'AmigoController');
    Route::resource('emprestimos', 'EmprestimoController');
    Route::resource('mensagens', 'MensagemController');
    Route::resource('comentarios', 'ComentarioController');
    Route::resource('lista', 'ListaDeDesejosController');

});

app/Http/Controllers/RevistaController.php
<?php
/**
 * Created by PhpStorm.
 * User: lucas
 * Date: 25/11/18
 * Time: 23:46
 */

namespace App\Http\Controllers;


use App\Entities\ListaDeDesejos;
use App\Entities\Revista;
use App\Http\Requests\Revista\StoreRevistaRequest;
use Illuminate\Http\Request;


class RevistaController extends Controller
{

    public function list(Request $request)
    {
        $search = $request->input('search');
        $disponivel = $request->input('disponivel');

        if($search)
        {
            $revistas = Revista::where('sub_titulo', 'like', "%$search%")
                ->get()
                ->each(function ($revista){
                    $revista->inList = ListaDeDesejos::verifyItem($revista->id);
                });
        }
        elseif($disponivel)
        {
            $filter = auth()->user()->emprestimos()
                ->whereNull('data_devolucao')
                ->get()
                ->flatMap(function ($emprestimo )
                {
                    return $emprestimo->itens->pluck('revista_id');
                });

            $itens = auth()->user()->colecoes->flatMap(
                function($colecao) use ($filter){
                    {
                        return $colecao->itens->whereNotIn('id', $filter);
                    }
                });

            $revistas  = $itens->each(
                function ($revista){
                    return $revista->sub_titulo = $revista->colecao->titulo->nome  .' - '. $revista->numero_volume .' - '. $revista->sub_titulo;
                })
                ->pluck('sub_titulo', 'id');
        }
        else
        {
            $revistas = null;
        }

        return $revistas;
    }


    public function show($id)
    {
        $revista = Revista::findOrFail($id);

        $comentarios = $revista->comentarios()->paginate();

        return view('revistas.show', compact('revista', 'comentarios'));
    }

    public function edit($id)
    {
        $revista = Revista::findOrFail($id);

        $count = auth()->user()->colecoes->find($revista->colecao_id);

        if(isset($count))
            return $revista;
    }

    public function store(StoreRevistaRequest $request)
    {
        $revista = Revista::create(array_except(
            $request->validated(), ['imagem']
        ));

        if($request->has('imagem')){
            $revista->setImage($request['imagem']);
        }

        $revista->save();

        alert()->success('OK !','Dados inseridos com sucesso');
        return redirect()->route('colecoes.itens.list', $revista->colecao_id);
    }

    public function update($id, StoreRevistaRequest $request)
    {
        $revista = Revista::findOrFail($id);

        if($revista){
            $revista->fill(array_except(
                $request->validated(), ['imagem']
            ));

            if($request->has('imagem')){
                $revista->setImage($request['imagem']);
            }

            $revista->save();

            alert()->success('OK !','Dados Atualizados com sucesso');
        }
        else{
            alert()->error('Erro !','Dado não localizado');
        }

        return redirect()->route('colecoes.itens.list', $revista->colecao_id);
    }

    public function destroy($id)
    {
        $revista = Revista::findOrFail($id);

        $colecaoDoUsuario = auth()->user()->colecoes->find($revista->colecao_id);

        if($revista->isFree() && isset($colecaoDoUsuario))
        {
            ListaDeDesejos::where('revista_id',$revista->id)
                ->get()
                ->each(function ($lista){
                    $lista->delete();
                });

            $revista->delete();

            return [
                'data' => [
                    'status' => 'success',
                    'message' => 'Excluído com sucesso!',
                    'info'    => 'Recarregando em 2 segundos...',
                    'code' => 204
                ]
            ];
        }

        return [
            'data' => [
                'status' => 'error',
                'message' => 'Não é possível excluir !',
                'info'    => 'Existem empréstimos em abrerto vinculados a essa coleção',
                'code' => 401
            ]
        ];
    }

    public function marcarParaVenda(Revista $revista)
    {
        $colecaoDoUsuario = auth()->user()->colecoes->find($revista->colecao_id);

        if($colecaoDoUsuario){

            $revista->vender = true;

            $revista->save();

            return [
                'data' => [
                    'status' => 'success',
                    'message' => 'Item marcado para venda com sucesso!',
                    'info'    => 'Recarregando em 2 segundos...',
                    'code' => 204
                ]
            ];
        }

        return [
            'data' => [
                'status' => 'error',
                'message' => 'Não é possível marcar o item para venda !',
                'info'    => 'O usuário não é o dono dessa revista',
                'code' => 401
            ]
        ];
    }

    public function desmarcarParaVenda(Revista $revista)
    {
        $colecaoDoUsuario = auth()->user()->colecoes->find($revista->colecao_id);

        if($colecaoDoUsuario){

            ListaDeDesejos::where('revista_id',$revista->id)
                ->get()
                ->each(function ($lista){
                    $lista->delete();
                });

            $revista->vender = false;

            $revista->save();

            return [
                'data' => [
                    'status' => 'success',
                    'message' => 'Item desmarcado para venda com sucesso!',
                    'info'    => 'Recarregando em 2 segundos...',
                    'code' => 204
                ]
            ];
        }

        return [
            'data' => [
                'status' => 'error',
                'message' => 'Não é possível desmarcar o item para venda !',
                'info'    => 'O usuário não é o dono dessa revista',
                'code' => 401
            ]
        ];
    }


    public function tipos()
    {
        return $tipos = [
            1 => 'Mangá',
            2 => 'Manhwha'
        ];
    }


}

resources/views/revistas/another_user_index.blade.php
@extends('template.template')

@section('breacumbs')
    <ol class="breadcrumb hidden-xs">
        <li class="active">
            <a href="{{ route('home') }}">
                <i class="voyager-home" ></i> Principal
            </a>
        </li>
        <li>
            <a href="{{ route('colecoes.index') }}">
                Coleções
            </a>
        </li>
        <li>Itens</li>
    </ol>
@endsection

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-archive"></i>{{ 'Itens da coleção: '.$colecao->titulo->nome .' - Proprietário: '. $colecao->usuario->name }}
        </h1>
    </div>

    <div id="gradient_bg"></div>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ HTML::ul($errors->all()) }}
                </div>
            @endif

            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                    <table  class="table datatable-export" style="width:100%" align="center">
                                        <thead>
                                        <tr>
                                            <th>Volume Nº</th>
                                            <th>Miniatura</th>
                                            <th>Subtítulo</th>
                                            <th>Data de lançamento</th>
                                            <th>Tipo</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @forelse($itens as $revista)
                                            <tr>
                                                <td>{{ $revista->numero_volume  }}</td>
                                                <td>
                                                    <img src="{{ $revista->imagem  }}" alt="Miniatura" class="capa" style="width: 36px; height: 36px; border: 1px solid rgb(34,166,239);">
                                                </td>
                                                <td>{{ $revista->sub_titulo }}</td>
                                                <td>{{ date('d/m/Y', strtotime($revista->lancamento)) }}</td>
                                                <td>{{ $revista->getTipo() }}</td>

                                                <td id="bread-actions" align="center">
                                                    <a class=" btn btn-sm btn-success pull-center view"
                                                       href="{{ route('revistas.show', $revista->id) }}"
                                                       title="Vizualizar"
                                                    >
                                                        <i class="not-active voyager-eye"></i>
                                                    </a>

                                                    @if($revista->vender && !in_array($revista->id, $minhaLista) )
                                                        {{ Form::open(['route' => ['lista.store'],'class'=>'form-horizontal', 'method' => 'POST']) }}

                                                        {{ csrf_field() }}

                                                        {!! Form::hidden('revista_id', $revista->id ?? null) !!}
                                                        <button title="Adicionar a Lista de desejos" class="btn btn-sm btn-primary pull-center"
                                                                type="submit"
                                                        >
                                                            <i class="not-active voyager-gift"></i>
                                                        </button>
                                                    @endif


                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="6" align="center">Nenhum dado cadastrado até o momento</td>
                                            </tr>
                                        @endforelse

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/revistas/index.blade.php
@extends('template.template')

@section('breacumbs')
    <ol class="breadcrumb hidden-xs">
        <li class="active">
            <a href="{{ route('home') }}">
                <i class="voyager-home" ></i> Principal
            </a>
        </li>
        <li>
            <a href="{{ route('colecoes.index') }}">
                Coleções
            </a>
        </li>
        <li>Itens</li>
    </ol>
@endsection

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-archive"></i>{{ 'Itens da coleção: '.$colecao->titulo->nome }}
        </h1>
        <a class="btn btn-success btn-add-new openModal"
           data-toggle="modal"
           data-target="#formModal"
           data-action="{{ route('revistas.store') }}"
           data-method="{{ 'POST' }}"
           data-colecao="{{ $colecao->id }}"
           data-title="{{ " Adicionar Cadastro " }}"
        >
            <i class="not-active voyager-plus"></i> {{ 'Adicionar item' }}
        </a>
    </div>

    <div id="gradient_bg"></div>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ HTML::ul($errors->all()) }}
                </div>
            @endif

            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                    <table  class="table datatable-export" style="width:100%" align="center">
                                        <thead>
                                        <tr>
                                            <th>Volume Nº</th>
                                            <th>Miniatura</th>
                                            <th>Subtítulo</th>
                                            <th>Data de lançamento</th>
                                            <th>Tipo</th>
                                            <th>Disponível</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @forelse($itens as $revista)
                                            <tr>
                                                <td>{{ $revista->numero_volume  }}</td>
                                                <td>
                                                    <img src="{{ $revista->imagem  }}" alt="Miniatura" class="capa" style="width: 36px; height: 36px; border: 1px solid rgb(34,166,239);">
                                                </td>
                                                <td>{{ $revista->sub_titulo }}</td>
                                                <td>{{ date('d/m/Y', strtotime($revista->lancamento)) }}</td>
                                                <td>{{ $revista->getTipo() }}</td>
                                                @if($revista->isFree())
                                                    <td><i class="voyager-check success"> Sim</i></td>
                                                @else
                                                    <td><i class="voyager-x danger"></i> Não</td>
                                                @endif

                                                <td id="bread-actions" align="center">
                                                    <a class=" btn btn-sm btn-success pull-center view"
                                                       href="{{ route('revistas.show', $revista->id) }}"
                                                       title="Vizualizar"
                                                    >
                                                        <i class="not-active voyager-eye"></i>
                                                    </a>

                                                    <button title="Editar" class="btn btn-sm btn-primary pull-center edit openModal"
                                                            data-toggle="modal"
                                                            data-target="#formModal"
                                                            data-action="{{route('revistas.update', $revista->id)}}"
                                                            data-method="{{'PUT'}}"
                                                            data-title="{{ " Alterar Cadastro " }}"
                                                            data-id="{{ $revista->id }}"
                                                    >
                                                        <i class="not-active voyager-edit"></i>
                                                    </button>

                                                    @if($revista->vender)
                                                        <button title="Desmarcar para venda" class="btn btn-sm btn-dark pull-center desmarcar"
                                                                href="#"
                                                                data-action="{{ route('revistas.desmarcar-para-venda', $revista->id) }}"
                                                                data-redirect="{{ route('colecoes.itens.list', $revista->colecao_id) }}"
                                                        >
                                                            <i class="not-active voyager-fire"></i>
                                                        </button>
                                                    @else
                                                        <button title="Marcar para venda" class="btn btn-sm btn-warning pull-center marcar"
                                                                href="#"
                                                                data-action="{{ route('revistas.marcar-para-venda', $revista->id) }}"
                                                                data-redirect="{{ route('colecoes.itens.list', $revista->colecao_id) }}"
                                                        >
                                                            <i class="not-active voyager-fire"></i>
                                                        </button>
                                                    @endif


                                                    <button title="Delete" class="btn btn-sm btn-danger pull-center delete"
                                                            href="#"
                                                            data-action="{{ route('revistas.destroy', $revista->id) }}"
                                                            data-redirect="{{ route('colecoes.itens.list', $revista->colecao_id) }}"
                                                    >
                                                        <i class="not-active voyager-trash"></i>
                                                    </button>

                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" align="center">Nenhum dado cadastrado até o momento</td>
                                            </tr>
                                        @endforelse

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <revista></revista>

@endsection

resources/views/revistas/show.blade.php
@extends('template.template')

@section('breacumbs')
    <ol class="breadcrumb hidden-xs">
        <li class="active">
            <a href="{{ route('home') }}">
                <i class="voyager-home" ></i> Principal
            </a>
        </li>
        <li>Revista</li>
    </ol>
@endsection

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="voyager-book"></i>{{ $revista->getTipo() .' : '. $revista->colecao->titulo->nome  .' nº '. $revista->numero_volume .' - '. $revista->sub_titulo }}
        </h1>
    </div>

    <div id="gradient_bg"></div>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">

            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ HTML::ul($errors->all()) }}
                </div>
            @endif

            <div class="col-md-12">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">
                            <div class="form-group" align="center">
                                <h5 align="left">Preview: </h5>
                                <hr>
                                <img src="{{ $revista->imagem ?? asset('vendor/images/icon-no-image.png') }}"
                                     style="width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:10px;" />
                                <p><strong> Nome: </strong>{{ $revista->sub_titulo }}</p>
                                <p><strong> Lançamento: </strong>{{ date('d/m/Y', strtotime($revista->lancamento)) }}</p>
                                <p><strong> Editora: </strong>{{ $revista->editora }}</p>
                                <p><strong> Obra: </strong>{{ $revista->colecao->titulo->nome }}</p>
                                <p><strong> Volume: </strong>{{ $revista->numero_volume }}</p>
                                <p><strong> Proprietário: </strong>{{ $revista->colecao->usuario->name }}</p>
                            </div>
                            <hr>

                            <div class="form-group">
                                <h5>Resumo da Obra:</h5>
                                <p>{{ $revista->colecao->titulo->resumo }}</p>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>


                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <div class="panel-body">

                            {{ Form::open(['route' => ['comentarios.store'],'class'=>'form-horizontal', 'method' => 'POST']) }}

                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="descricao"><h5>Deixe seu comentário:</h5></label>
                                    {!! Form::hidden('revista', $revista->id ?? null) !!}
                                    {!! Form::textarea('descricao', '',['class'=>'form-control', 'rows' => 3,'placeholder'=>'Comentário' , 'required']) !!}
                                    <br>
                                    <button type="submit" class="btn btn-primary pull-right">
                                        <i class="voyager-paper-plane"></i>
                                        <span> Postar</span>
                                    </button>
                                </div>
                            </div>


                            <div>
                                <h5>Comentários: </h5>
                                <table class="table">
                                    <tbody>
                                    @forelse($comentarios as $comentario)
                                    <tr>
                                        <td width="80">
                                            <img src="{{ $comentario->usuario->avatar ?? asset('/vendor/images/user_default.png') }}"
                                                 class="avatar"
                                                 style="border-radius:50%; width:60px; height:60px; border:5px solid #fff;"
                                                 alt="{{ $comentario->usuario->name }} avatar">
                                        </td>
                                        <td style="text-align: left">
                                            <p><strong> {{ ucwords( $comentario->usuario->name) }} </strong></p>
                                            <p>"{{ $comentario->descricao }}"</p>
                                            <p class="text-info font-size-10">Comentado em: {{ $comentario->created_at->format('d/m/Y') ?? '' }}</p>
                                        </td>
                                        <td width="10">
                                            @if($comentario->usuario->id == auth()->user()->id)
                                                <button title="Delete" class="btn btn-sm btn-danger pull-center delete"
                                                        href="#"
                                                        data-action="{{ route('comentarios.destroy', $comentario->id) }}"
                                                        data-redirect="{{ route('revistas.show', $revista->id) }}"
                                                >
                                                    <i class="not-active voyager-trash"></i>
                                                </button>
                                            @endif
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td>Nenhum Comentário até o momento</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>

                            {{ $comentarios->links() }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection