routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Auth\RedirectController@redirect')->middleware('auth');

Route::group(['middleware' => ['auth']], function () {

    //PAGINA PRINCIPAL
    Route::get('/home', 'HomeController@index')
        ->name('home');

    //PERFIL PESSOAL
    Route::get('/my-profile', 'UserController@myProfile')
        ->name('myprofile.index');

    Route::get('/my-profile/edit', 'UserController@myProfileEdit')
        ->name('myprofile.edit');

    //COLEÇÕES AMIGOS E REVISTAS
    Route::get('colecoes/{colecao}/itens', 'ColecaoController@listItens')
        ->name('colecoes.itens.list');

    Route::get('amigos/list', 'AmigoController@list')
        ->name('amigos.list');

    Route::get('revistas/list', 'RevistaController@list')
        ->name('revistas.list');

    Route::get('revistas/tipos', 'RevistaController@tipos')
        ->name('revistas.tipos');

    Route::post('revistas/{revista}/marcar-para-venda', 'RevistaController@marcarParaVenda')
        ->name('revistas.marcar-para-venda');

    Route::post('revistas/{revista}/desmarcar-para-venda', 'RevistaController@desmarcarParaVenda')
        ->name('revistas.desmarcar-para-venda');

    Route::post('emprestimos/{emprestimo}/devolver', 'EmprestimoController@devolver')
        ->name('emprestimos.devolver');

    Route::get('users/list', 'UserController@list')
        ->name('users.list');

    Route::get('search', 'BuscaController@index')
        ->name('search.index');

    //CRUDS
    Route::resource('users', 'UserController');
    Route::resource('titulos', 'TituloController');
    Route::resource('colecoes', 'ColecaoController');
    Route::resource('revistas', 'RevistaController');
    Route::resource('amigos', 'AmigoController');
    Route::resource('emprestimos', 'EmprestimoController');
    Route::resource('mensagens', 'MensagemController');
    Route::resource('comentarios', 'ComentarioController');
    Route::resource('lista', 'ListaDeDesejosController');

});

resources/views/template/footer_scripts.blade.php
<script>
    (function(){
        let appContainer = document.querySelector('.app-container'),
            sidebar = appContainer.querySelector('.side-menu'),
            navbar = appContainer.querySelector('nav.navbar.navbar-top'),
            loader = document.getElementById('voyager-loader'),
            hamburgerMenu = document.querySelector('.hamburger'),
            sidebarTransition = sidebar.style.transition,
            navbarTransition = navbar.style.transition,
            containerTransition = appContainer.style.transition;

        sidebar.style.WebkitTransition = sidebar.style.MozTransition = sidebar.style.transition =
            appContainer.style.WebkitTransition = appContainer.style.MozTransition = appContainer.style.transition =
                navbar.style.WebkitTransition = navbar.style.MozTransition = navbar.style.transition = 'none';

        if (window.localStorage && window.localStorage['voyager.stickySidebar'] == 'true') {
            appContainer.className += ' expanded no-animation';
            loader.style.left = (sidebar.clientWidth/2)+'px';
            hamburgerMenu.className += ' is-active no-animation';
        }

        navbar.style.WebkitTransition = navbar.style.MozTransition = navbar.style.transition = navbarTransition;
        sidebar.style.WebkitTransition = sidebar.style.MozTransition = sidebar.style.transition = sidebarTransition;
        appContainer.style.WebkitTransition = appContainer.style.MozTransition = appContainer.style.transition = containerTransition;
    })();
</script>

{!! HTML::script('vendor/js/app.js')!!}
{!! HTML::script('vendor/sweetalert/sweetalert.all.js')!!}
{!! HTML::script('js/functions.js')!!}
{!! HTML::script('js/app.js')!!}

resources/views/template/main_navigation.blade.php
<div class="side-menu sidebar-inverse">
    <nav class="navbar navbar-default" role="navigation">
        <div class="side-menu-container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <div class="logo-icon-container">
                        <img src="{{ URL::asset('vendor/images/logo-icon-light.png') }}" alt="Logo Icon">
                    </div>
                    <div class="title">{{env('APP_NAME') ?? 'iOtaku'}}</div>
                </a>
            </div><!-- .navbar-header -->

            <div class="panel widget center bgimage"
                 style="background-image:url(/vendor/images/bg.jpg); background-size: cover;
                 background-position: 0px;">

                <div class="dimmer"></div>
                <div class="panel-content">
                    <img src="{{ auth()->user()->avatar ?? URL::asset('vendor/images/user_default.png') }}"
                         class="avatar" alt="Avatar"
                         style="width: 40px; height: 40px;background-position: 50% 50%; background-size: auto 100%; border:2px solid #14ff26;"
                    >
                    <h4>&emsp; {{ auth()->user()->name }}</h4>
                    <div style="clear:both"></div>
                </div>
            </div>

        </div>

        <ul class="nav navbar-nav">
            <li class="active">
                <a href="{{url('/')}}" target="_self">
                    <span class="icon voyager-home"></span>
                    <span class="title">Principal</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('colecoes.index') }}" target="_self">
                    <span class="icon voyager-archive"></span>
                    <span class="title">Coleções</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('amigos.index') }}" target="_self">
                    <span class="icon voyager-people"></span>
                    <span class="title">Amigos</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('emprestimos.index') }}" target="_self">
                    <span class="icon voyager-book"></span>
                    <span class="title">Empréstimos</span>
                </a>
            </li>

            <li class="">
                <a href="{{ route('lista.index') }}" target="_self">
                    <span class="icon voyager-gift"></span>
                    <span class="title">Minha Lista</span>
                </a>
            </li>

        </ul>

    </nav>
</div>

resources/views/template/navbar.blade.php
<nav class="navbar navbar-default navbar-fixed-top navbar-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="hamburger btn-link">
                <span class="hamburger-inner"></span>
            </button>
            @yield('breacumbs')
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown profile">
                <a href="#" class="dropdown-toggle text-right" data-toggle="dropdown" role="button"
                   aria-expanded="false">
                    <img src="{{ URL::asset('vendor/images/helm.png') }}" class="profile-img">
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-animated">
                    <li class="profile-img">
                        <img src="{{ auth()->user()->avatar ?? URL::asset('vendor/images/user_default.png') }}" class="profile-img">
                        <div class="profile-body">
                            <h4 style="font-size: medium">{{auth()->user()->name}}</h4>
                            <a href="{{ route('myprofile.index') }}" >
                                <i class="voyager-person"></i>
                                Perfil do usuário
                            </a>
                        </div>

                    </li>
                    <li class="divider"></li>
                    <li>
                        <form action="{{ route('logout') }}" method="POST" id="logout-form">
                            {{ csrf_field() }}
                            <button class="logout btn btn-danger btn-block">
                                <i class="voyager-power"></i>
                                Logout
                            </button>
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/template/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{env('APP_NAME')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ URL::asset('vendor/images/logo-icon.png') }}" type="image/x-icon">

    @include('template.header_css')
    @yield('css')

    {{--ziggy library--}}
    @routes
</head>

<body class="voyager">
    <div id="app">
        <div id="voyager-loader">
            <img src="{{ URL::asset('vendor/images/loading.png') }}" alt="Voyager Loader">
        </div>

        <div class="app-container">
            <div class="fadetoblack visible-xs"></div>
            <div class="row content-container">
            @include('template.navbar')
            @include('template.main_navigation')

            <!-- Main Content -->
                <div class="container-fluid">
                    <div class="side-body padding-top">
                        @yield('page_header')
                        <div id="voyager-notifications"></div>
                        <div class="page-content">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->

    @include('template.footer_scripts')
    @include('sweetalert::alert')
    @include('shared.messages')
    @stack('scripts')

    <footer class="app-footer">
        <div class="site-footer-right" style="font-size: smaller">
            <a>Desenvolvido por Lucas Nunes</a> - v1.0
        </div>
    </footer>

</body>
</html>